name: Linting and type checking

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check linting
        run: deno fmt --check .

  check-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check typing
        run: deno lint

  check-typing:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install dependencies
        run: deno install

      - name: Check typing
        run: deno check --doc .
